const Images = {
    english: require('../../assets/images/english.png'),
    urdu: require('../../assets/images/urdu.png'),
    splash_background: require('../../assets/images/Splash_Background.png'),
    splash_logo: require('../../assets/images/Splash_Logo.png'),
    signIn: require('../../assets/images/signin-image.png'),
    signUp: require('../../assets/images/Signup-Image.png'),
    person: require('../../assets/images/Person.png'),
    lock: require('../../assets/images/lock.png'),
    mail: require('../../assets/images/mail.png'),
    logout: require('../../assets/images/logout.png'),
    head_drawer: require('../../assets/images/head_drawer.png'),
    foot_drawer: require('../../assets/images/foot_drawer.png'),
    land: require('../../assets/images/land.png'),
    labour: require('../../assets/images/labour.png'),
    expense: require('../../assets/images/expense.png'),
    support: require('../../assets/images/support.png'),
    star: require('../../assets/images/star.png'),
    about: require('../../assets/images/about.png'),
    setting: require('../../assets/images/setting.png'),
    foot_drawer: require('../../assets/images/foot_drawer.png'),
    home: require('../../assets/images/home.png'),
    land_button: require('../../assets/images/land_button.png'),
    land_name: require('../../assets/images/land_name.png'),
    area: require('../../assets/images/area.png'),
    expenses: require('../../assets/images/expenses.png'),
    goods: require('../../assets/images/goods.png'),
    attendence: require('../../assets/images/attendence.png'),
    price: require('../../assets/images/price.png'),
    calander: require('../../assets/images/calander.png'),
    white_bg: require('../../assets/images/white_bg.png'),
}

export default Images;