export default {
    APP_TITLE: 'Meri Zameen',
    EMAIL_ADDRESS: 'E-mail Address',
    PASSWORD: 'Password',
    LOG_IN: 'Log In',
    OR: 'OR',
    SIGN_UP: 'Sign Up',
    NAME: 'Name',
    LAND_MANAGEMENT: 'Land Management',
    MY_LANDS: 'My Lands',
    LABOUR_MANAGEMENT: 'Labour Management',
    BACK: 'Back',
    ADD: 'Add Land',
    LAND_NAME: 'Land Name',
    LAND_AREA: 'Land Area',
    LAND_TYPE: 'Land Type',
    OWNER: 'Owner',
    RENT: 'Rent',
    SUBMIT: 'Submit',
    RENT_PER_ACRE: 'Rent Per Acre',
    EXPENSE: 'Expense',
    SELL: 'Sell',
    LAND_DETAIL_ENROLL: 'Land Detail Enroll',
    LABOUR_ENROLL: 'Labour Enroll',
    DETAIL: 'Detail',
    CROP_AREA: 'Crop Area',
    CROP_SEASON: 'Crop Season',
    CROP_TYPE: 'Crop Type',
    CROP: 'Crop....',
    EG_2022: 'e.g. 2022',
    EG_3_ACRE: 'e.g. 3 acre',
    LABOUR_NAME: 'Labour Name',
    TYPE: 'Type',
    LABOUR_TYPE: 'Labour Type....',
    LABOURTYPE: 'Labour Type',
    WAGE: 'Wage',
    PER_DAY: 'Per day',
    PER_MONTH: 'Per month',
    PRICE: 'Price',
    LABOUR: 'Labour',
    LABOUR_PAYMENT: 'Labour Payment',
    BUYING: 'Buying',
    OTHER: 'Other',
    GIVEN_AMOUNT: 'Given Amount',
    BUY: 'Buy',
    BUY_TYPE: 'Buy Type',
    AMOUNT: 'Amount',
    ADD_NAME: 'Add Name',
    DETAILS: 'Details',
    SELL: 'Sell',
    SELLING_AMOUNT: 'Selling Amount',
    ATTENDENCE: 'Attendance',
    DATE: 'Date',
    ACTIVE_LABOUR: 'Active Labour',
    START_DATE: 'Start Date',
    END_DATE: 'End Date',
    PRESENT_DATES: 'Present Dates',
    PRESENT_DAYS: 'Present Days',
    PER_DAY_WAGE: 'Per day wage',
    TOTAL: 'Total',
    LOG_OUT: 'Log out',
    ALERT: 'Alert',
    PLEASE_ENTER_NAME: 'Please enter name',
    OK: 'OK',
    PLEASE_ENTER_EMAIL: 'Please enter Email',
    INCORRECT_EMAIL: 'Incorrect Email',
    PLEASE_ENTER_PASSWORD: "Please enter password",
    CHARACTERS: 'Password will be minimum 6 characters',
    PLEASE_ENTER_LAND_NAME: "Please enter land name",
    PLEASE_ENTER_LAND_AREA: "Please enter land area",
    PLEASE_SELECT_LAND_TYPE: "Please select land type",
    PLEASE_ENTER_RENT: "Please enter rent",
    PLEASE_ENTER_LABOUR_NAME: "Please enter labour name",
    PLEASE_ENTER_LABOUR_TYPE: "Please select labour type",
    PLEASE_SELECT_WAGE: "Please select wage",
    PLEASE_ENTER_PRICE: "Please enter price",
    PLEASE_ENTER_GIVEN_AMOUNT: "Please enter given amount",
    PLEASE_SELECT_BUY_TYPE: "Please select buy type",
    PLEASE_ENTER_DETAILS: "Please enter details",
    DATE: 'Date',
    CONFIRM: 'CONFIRM',
    CANCEL: 'CANCEL',
    ABSENT: 'Absent',
    ABSENT_DAYS: 'Absent Days',
    ABSENT_DATES: 'Absent Dates',
    PER_MONTH_WAGE: 'Per month wage',
    TOTAL_FINE: 'Total fine',
    FINE_PER_DAY: 'Fine per day',
    SELECT_CROP_TYPE: 'Select crop type',
    PLEASE_ENTER_CROP_SEASON: 'Please enter crop season',
    PLEASE_ENTER_CROP_AREA: 'Please enter crop area',
    REPORT: 'Report',
    SEASON: 'Season',
    RS: 'Rs',
    TOTAL_PROFIT: 'Total Profit',
    TOTAL_LOSS: 'Total Loss',
};