export default {
    APP_TITLE: 'میری زمین',
    EMAIL_ADDRESS: 'ای-میل اڈریس',
    PASSWORD: 'پاس ورڈ',
    LOG_IN: 'لاگ ان کریں',
    OR: 'یا',
    SIGN_UP: 'سائن اپ',
    NAME: 'نام',
    LAND_MANAGEMENT: 'زمین کا انتظام',
    MY_LANDS: 'میری زمینیں',
    LABOUR_MANAGEMENT:'لیبر مینجمنٹ',
    BACK: 'پیچھے',
    ADD: 'شامل کریں',
    LAND_NAME: 'زمین کا نام',
    LAND_AREA: 'زمین کا علاقہ',
    LAND_TYPE: 'زمین کی قسم',
    OWNER: 'مالک',
    RENT: 'کرایہ',
    SUBMIT: 'جمع کرائیں',
    RENT_PER_ACRE: 'کرایہ فی ایکڑ',
    EXPENSE: 'خرچہ',
    SELL: 'بیچنا',
    LAND_DETAIL_ENROLL: 'زمین کی تفصیلات کا اندراج',
    LABOUR_ENROLL: 'لیبر اندراج',
    DETAIL: 'تفصیل',
    CROP_AREA: 'فصل کا رقبہ',
    CROP_SEASON: 'فصل کا موسم',
    CROP_TYPE: 'فصل کی قسم',
    CROP: 'فصل....',
    EG_2022: 'جیسے 2022',
    EG_3_ACRE: 'جیسے 3 ایکڑ',
    LABOUR_NAME: 'مزدور کا نام',
    TYPE: 'قسم',
    LABOUR_TYPE: 'لیبر کی قسم....',
    LABOURTYPE: 'لیبر کی قسم',
    WAGE: 'اجرت',
    PER_DAY: 'فی دن',
    PER_MONTH: 'فی مہینہ',
    PRICE: 'قیمت',
    LABOUR: 'مزدور',
    LABOUR_PAYMENT: 'مزدوری کی ادائیگی',
    BUYING: 'خریدنا',
    OTHER: 'دیگر',
    GIVEN_AMOUNT: 'دی گئی رقم',
    BUY: 'خریدنے',
    BUY_TYPE: 'قسم خریدیں',
    AMOUNT: 'رقم',
    ADD_NAME: 'نام شامل کریں',
    DETAILS: 'تفصیلات',
    SELL: 'بیچنا',
    SELLING_AMOUNT: 'فروخت کی رقم',
    ATTENDENCE: 'حاضری',
    DATE: 'تاریخ',
    ACTIVE_LABOUR: 'فعال لیبر',
    START_DATE: 'شروع کرنے کی تاریخ',
    END_DATE: 'آخری تاریخ',
    PRESENT_DATES: 'موجودہ تاریخیں۔',
    PRESENT_DAYS: 'موجودہ دن',
    PER_DAY_WAGE: 'یومیہ اجرت',
    TOTAL: 'کل',
    LOG_OUT: 'لاگ آوٹ',
    ALERT: 'الرٹ',
    PLEASE_ENTER_NAME: 'براہ کرم نام درج کریں۔',
    OK: 'ٹھیک ہے',
    PLEASE_ENTER_EMAIL: 'براہ کرم ای میل درج کریں۔',
    INCORRECT_EMAIL: 'غلط ای میل',
    PLEASE_ENTER_PASSWORD: "براہ کرم پاس ورڈ درج کریں۔",
    CHARACTERS: 'پاس ورڈ کم از کم 6 حروف کا ہوگا۔',
    PLEASE_ENTER_LAND_NAME: "براہ کرم زمین کا نام درج کریں۔",
    PLEASE_ENTER_LAND_AREA: "براہ کرم زمین کا علاقہ درج کریں۔",
    PLEASE_SELECT_LAND_TYPE: "براہ کرم زمین کی قسم منتخب کریں۔",
    PLEASE_ENTER_RENT: "براہ کرم کرایہ درج کریں۔",
    PLEASE_ENTER_LABOUR_NAME: "براہ کرم لیبر کا نام درج کریں۔",
    PLEASE_ENTER_LABOUR_TYPE: "براہ کرم لیبر کی قسم منتخب کریں۔",
    PLEASE_SELECT_WAGE: "براہ کرم اجرت کا انتخاب کریں۔",
    PLEASE_ENTER_PRICE: "براہ کرم قیمت درج کریں۔",
    PLEASE_ENTER_GIVEN_AMOUNT: "براہ کرم دی گئی رقم درج کریں۔",
    PLEASE_SELECT_BUY_TYPE: "براہ کرم خرید کی قسم منتخب کریں۔",
    PLEASE_ENTER_DETAILS: "براہ کرم تفصیلات درج کریں۔",
    DATE: 'تاریخ منتخب کریں',
    CONFIRM: 'تصدیق کریں',
    CANCEL: 'منسوخ کریں',
    ABSENT: 'غیر حاضر',
    ABSENT_DAYS: 'غیر حاضر دن',
    ABSENT_DATES: 'غیر حاضر تاریخیں',
    PER_MONTH_WAGE: 'ماہانہ اجرت',
    TOTAL_FINE: 'مکمل جرمانہ',
    FINE_PER_DAY: 'فی دن ٹھیک',
    SELECT_CROP_TYPE: 'فصل کی قسم منتخب کریں۔',
    PLEASE_ENTER_CROP_SEASON: 'براہ کرم فصل کا موسم درج کریں۔',
    PLEASE_ENTER_CROP_AREA: 'براہ کرم فصل کا علاقہ درج کریں۔',
    REPORT: 'رپورٹ',
    SEASON: 'موسم',
    RS: 'روپے',
    TOTAL_PROFIT: 'کل منافع',
    TOTAL_LOSS: 'کل نقصان',
};